### ISSUE TITLE
Clean session flag

### ISSUE THREAD

**Issue by planer-pro** [olliephillips/tinyMQTT#10]
Hi, how i can transfer clean session flag information, in order to all transferred data will be cleaning after disconnect? (how it implemented in official MQTT lib for espruino) 
Transfer like:
`
var server = "m14.cloudmqtt.com";
var options = {
    port: 1234,
    clean_session: true,
    username: "qwerty",
    password: "qwerty",
};
var mqtt = require("https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.min.js").create(server, options);
`
Not doing clean session, and information always remains on mqtt server after disconnect.

**Comment by olliephillips** [comment]
The clean session flag isn't implemented in tinyMQTT. It's an aspect that was left out in order to reduce the size of the module as far as possible (to get it to fit and leave room for program code in early days of ESP8226 Espruino port). The RAM constraints have since eased so you could probably add it back by following the core MQTT espruino module - on which this was based (I'm assuming you are using Espruino on ESP8226), but since there are now more js vars available, you may also be able to run the core MQTT module itself which, as you say, does support clean session.

**Comment by planer-pro** [comment]
Yes i am using esp8266. It is a pity that there is no this function! Well, I'll try to add this function to tinyMQTT

**Comment by olliephillips** [comment]
If you add it back then great, but have you tried the core MQTT module? Will that not work on ESP8266 given ram/js vars available now?
